<a href="https://colab.research.google.com/github/jmora420-hue/Ciencia_de_datos/blob/main/Ejercicio_taxi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Taxi_Trip_Pricing.csv")
df.head()

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35,Morning,Weekday,3,Low,Clear,3.56,0.8,0.32,53.82,36.2624
1,47.59,Afternoon,Weekday,1,High,Clear,NaN,0.62,0.43,40.57,NaN
2,36.87,Evening,Weekend,1,High,Clear,2.7,1.21,0.15,37.27,52.9032
3,30.33,Evening,Weekday,4,Low,NaN,3.48,0.51,0.15,116.81,36.4698
4,NaN,Evening,Weekday,3,High,Clear,2.93,0.63,0.32,22.64,15.618

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Trip_Distance_km       954 non-null    object
 1   Time_of_Day            954 non-null    object
 2   Day_of_Week            954 non-null    object
 3   Passenger_Count        954 non-null    object
 4   Traffic_Conditions     954 non-null    object
 5   Weather                954 non-null    object
 6   Base_Fare              954 non-null    object
 7   Per_Km_Rate            954 non-null    object
 8   Per_Minute_Rate        954 non-null    object
 9   Trip_Duration_Minutes  954 non-null    object
 10  Trip_Price             954 non-null    object
dtypes: object(11)
memory usage: 86.1+ KB

In [8]:
df.isnull().sum()

Trip_Distance_km         46
Time_of_Day              46
Day_of_Week              46
Passenger_Count          46
Traffic_Conditions       46
Weather                  46
Base_Fare                46
Per_Km_Rate              46
Per_Minute_Rate          46
Trip_Duration_Minutes    46
Trip_Price               46
dtype: int64

aseguraos que los numeros son numeros

In [12]:
columnas_numericas = [
    'Trip_Distance_km', 'Passenger_Count', 'Base_Fare',
    'Per_Km_Rate', 'Per_Minute_Rate', 'Trip_Duration_Minutes', 'Trip_Price'
]

for col in columnas_numericas:
    print(f"Valores únicos en {col}:", df[col].unique())

for col in columnas_numericas:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df.head()

Valores únicos en Trip_Distance_km: ['19.35' '47.59' '36.87' '30.33' nan '8.64' '3.85' '43.44' '30.45' '35.7'
 '48.53' '41.79' '11.4' '9.91' '9.99' '15.91' '26.71' '22.17' '15.27'
 '30.98' '7.84' '105.94355' '18.95' '23.35' '39.47' '10.78' '138.0983279'
 '30.03' '3.28' '30.77' '9.36' '4.19' '47.5' '48.32' '40.61' '15.93'
 '5.79' '34.53' '22.57' '6.98' '25.26' '2.69' '45.56' '13.68' '33.46'
 '16.27' '26.48' '27.79' '10.06' '48.51' '38.98' '47.04' '44.85' '30.3'
 '46.17' '5.34' '10.6' '3.22' '16.94' '20.05' '14.3' '41.61' '18.48'
 '146.0670472' '27.59' '7.91' '40.31' '4.65' '49.36' '38.84' '10.74'
 '1.27' '40.96' '35.64' '36.72' '38.79' '4.63' '18.56' '6.68' '43.29'
 '31.54' '17.21' '4.11' '?' '16.93' '36.75' '44.47' '24.14' '6.86' '35.95'
 '38.28' '28.5' '38.78' '26.61' '21.95' '2.25' '6.29' '2.54' '32.18'
 '16.4' '25.92' '45.47' '13.22' '21.11' '38.02' '112.8309583' '4.77'
 '102.7475562' '46.56' '40.6' '32.04' '43.7' '40.38' '10.14' '44.74'
 '27.43' '40.56' '44.91' '16.58' '6.39' '12.17' '21.93' '41.08' '43.18'
 '1.34' '26.03' '21.45' '11.88' '6.87' '17.54' '16.84' '26.42' '18.82'
 '48.62' '48.16' '109.616082' '15.74' '14.96' '2.81' '30.87' '25.63'
 '3.52' '14.65' '45.51' '12.74' '8.1' '24.98' '49.3' '12.86' '33.93'
 '38.32' '12.64' '36.68' '19.02' '31.98' '27.25' '5.42' '41.93' '3'
 '29.95' '34.2' '1.81' '26.09' '12.1' '32.61' '9.54' '34.86' '19.95'
 '46.9' '7.74' '17.71' '6.56' '46.31' '43.99' '13.64' '33.34' '41.04'
 '28.2' '26.95' '12.85' '5.56' '45.12' '32.02' '17.61' '18.11' '39.21'
 '32.46' '5.12' '8.92' '45.03' '30.72' '1.45' '5.97' '33.51' '1.25' '8.88'
 '27.89' '34.9' '32.95' '11.99' '35.9' '12.63' '37.58' '32.83' '42.61'
 '33.22' '28.85' '5.59' '13.99' '130.8090013' '48.68' '20.26' '44.71'
 '31.93' '39.95' '29.27' '25.13' '36.4' '14.76' '2.19' '32.63' '9.68'
 '47.08' '47.74' '45.83' '19.14' '1.76' '46.49' '21.98' '48.37' '48.22'
 '42.8' '15.43' '19.87' '42.71' '16.53' '9.31' '28.28' '46.87' '35.11'
 '28.93' '5.76' '31.14' '49.51' '7.86' '26.4' '37.3' '35.15' '116.1960636'
 '139.0622302' '40.66' '40.7' '43.49' '45.75' '26.06' '25.57' '40.12'
 '32.85' '35.4' '39.99' '44.61' '17.56' '5.61' '29.34' '2.76' '23.81'
 '100.38042' '15.04' '2.49' '2.83' '41.31' '18.65' '7.23' '26.59' '38.73'
 '11.58' '31.52' '5.18' '3.53' '27.04' '145.7470599' '32.23' '36.58'
 '48.82' '26.3' '16.82' '39.96' '14.27' '22.51' '4.84' '2.24' '48.17'
 '41.96' '35.1' '21.04' '9.49' '8.67' '13.26' '27.91' '36.02' '33.35'
 '14.72' '47.79' '37.16' '28.16' '21.56' '13.14' '18.44' '38.13' '1.71'
 '6.69' '3.25' '42.92' '35.48' '116.6676807' '25.09' '24.2' '22.26'
 '31.18' '32.12' '19.36' '31.67' '25.65' '42.97' '33.28' '8.98' '4.46'
 '32.48' '2.3' '47.07' '29.2' '20.02' '32.52' '23.45' '27.74' '47.13'
 '19.92' '45.36' '10.59' '4.4' '5.94' '1.89' '5.63' '34.47' '4.49' '16.63'
 '42.4' '2.14' '40.91' '14.81' '6.79' '35.14' '31.82' '44' '37.02' '40.37'
 '14.82' '9.69' '37.78' '40.53' '49.53' '21.22' '19.23' '39.04' '17.7'
 '46.61' '43.06' '22.02' '37.79' '37.97' '6.05' '25.76' '41.5' '44.88'
 '20.07' '1.53' '5.47' '104.3717909' '47.55' '47.58' '29.1' '31.96'
 '22.97' '15.37' '33.95' '37.87' '39.79' '39.69' '25.23' '27.93' '22.63'
 '44.5' '6.74' '8.01' '38.31' '31.29' '5.96' '35.35' '4.57' '41.27' '5.16'
 '49.35' '19.34' '19.16' '40.83' '47.42' '37.92' '19.44' '5.09' '39.08'
 '28.36' '21.79' '45.41' '6.45' '25.14' '1.56' '23.96' '3.76' '6.82'
 '6.76' '32.81' '37.56' '29.59' '48.15' '19.37' '15' '43.56' '11.96'
 '48.2' '48.52' '3.11' '44.67' '26.86' '49.66' '28.14' '48.5' '26.63'
 '31.84' '107.786832' '23.27' '31.75' '29.63' '45.16' '3.23' '14.77'
 '47.57' '44.62' '23.33' '31.39' '14.59' '10.22' '23.72' '18.31' '29.6'
 '4.81' '48.75' '49.32' '35.21' '27.27' '16.17' '40.88' '34.55' '8.97'
 '45.64' '41.3' '47.54' '36.56' '31.06' '21.49' '46.7' '2.29' '19.45'
 '40.72' '49.38' '8.37' '30.11' '19.66' '42.26' '42.08' '23.97' '21.33'
 '14.4' '43.37' '49.99' '139.4765146' '28.22' '38.68' '47.29' '42.63'
 '13.12' '23.08' '7.33' '47.75' '30.7' '12.2' '33.91' '18.55' '26.5'
 '26.49' '42.76' '28.04' '28.49' '43.96' '20.77' '7.57' '2.41' '38' '31.4'
 '35.5' '11.44' '7.68' '18.18' '29.91' '20.22' '22.44' '45.3' '18.06'
 '26.19' '39.4' '20.43' '31.48' '43.26' '47.53' '8.21' '46.4' '25.11'
 '13.65' '23.5' '49.02' '17.11' '12.77' '4.72' '7.32' '122.820191' '8.44'
 '7.8' '32.4' '17.94' '44.94' '24.22' '33.71' '9.44' '10.42' '9.28' '9.67'
 '5.35' '6.91' '23.58' '11.11' '18.85' '25.67' '34.83' '2.93' '40.17'
 '31.77' '5.01' '43.81' '46.12' '138.7638872' '14.57' '40.5' '37.66'
 '10.04' '11.26' '19.15' '24.74' '19.08' '23.66' '37.63' '2.8' '13.37'
 '44.87' '26.07' '27.07' '6.25' '22.92' '27.1' '12.88' '14.19' '19.49'
 '1.98' '11.36' '17.05' '44.64' '30.09' '39.67' '25.42' '5.26' '27.32'
 '29.76' '37.53' '22.15' '7.25' '14.91' '18.79' '32.65' '28.97' '18.45'
 '49.34' '30.68' '12.62' '5.99' '8.49' '13.05' '8.87' '14.97' '9.5' '4.93'
 '26.7' '49.14' '6.49' '20.49' '43.41' '9.37' '33.76' '46.54' '29.01'
 '38.71' '10.17' '16.86' '21.85' '25.87' '6.63' '30.92' '15.14' '29.48'
 '8.56' '24.58' '3.54' '17.49' '7.59' '16.8' '40.68' '13.48' '34.39'
 '38.25' '30.19' '24.11' '21.18' '18.09' '46.55' '41.7' '48.29' '7.09'
 '36.81' '46.98' '9.88' '4.26' '37.31' '29.15' '7.85' '39.97' '10.88'
 '9.02' '9.05' '33.59' '43.98' '20.23' '41.01' '22.52' '19.47' '23.67'
 '15.77' '12.38' '45.08' '19.81' '101.0397035' '45.42' '31.59' '6.73'
 '47.05' '31.76' '17.41' '7.82' '39.91' '31.38' '27.14' '44.8' '39.64'
 '8.43' '13.18' '37.45' '2.64' '28.92' '38.36' '17.76' '41.24' '42.48'
 '20.47' '8.35' '12.23' '36.39' '36.28' '32.42' '35' '13.34' '9.9' '20.64'
 '23.64' '8.51' '29.73' '25.79' '30.96' '43.73' '108.1469938' '46.2'
 '35.65' '8.47' '29.24' '30.73' '21.78' '37.09' '46.78' '46.35' '23.09'
 '6.55' '49.26' '42.11' '7.11' '43.62' '29.97' '20.55' '3.68' '17.42'
 '40.34' '1.23' '20.51' '27.33' '46.07' '17.97' '18' '37.14' '23.16'
 '23.17' '7.9' '9.64' '126.5476283' '18.76' '29.45' '1.64' '9.72' '48.09'
 '8.28' '49.85' '25.61' '30.17' '4.29' '37.75' '11.29' '45' '11.05'
 '10.34' '2.79' '24.13' '28.68' '4.22' '39' '23.21' '22.6' '28.42' '8.61'
 '43.23' '47.36' '19.29' '21.03' '8.65' '36.08' '33.29' '2.33' '12.32'
 '33.92' '1.97' '6.1' '40.2' '9.75' '32.98' '12.67' '5.87' '12.92' '42.93'
 '41.68' '20.46' '33.74' '11.04' '15.36' '44.92' '5.19' '11.19' '9.89'
 '29.57' '21.65' '41.05' '17.75' '13.71' '19.6' '29.92' '14.14' '31.58'
 '21.06' '28.05' '22.37' '47.47' '38.42' '7.87' '43.55' '24.88' '44.83'
 '40.19' '21.84' '2.1' '14.17' '27.54' '7.83' '41.91' '49.24' '26.76'
 '9.41' '14.34' '1.9' '45.8' '6.77' '14.43' '28.15' '32.92' '1.54' '7.71'
 '45.1' '43.82' '30.27' '30.43' '9.59' '45.81' '21.52' '19.77' '26.43'
 '3.3' '9.15' '5.06' '13.02' '20.08' '15.15' '18.43' '36.23' '15.56'
 '28.75' '24.33' '36.9' '11.53' '2.53' '13.85' '30.16' '25.32' '30.25'
 '17.38' '38.77' '6.22' '4.68' '25.28' '34.73' '22.31' '13.07' '41.14'
 '35.04' '18.69' '5.49' '45.95' '7.7' '47.56' '22.85']
Valores únicos en Passenger_Count: ['3' '1' '4' '2' nan '?']
Valores únicos en Base_Fare: ['3.56' nan '2.7' '3.48' '2.93' '2.55' '3.51' '2.97' '2.77' '3.39' '2.4'
 '4.78' '4.6' '4.12' '2.32' '4.33' '4.42' '4.3' '2.34' '3.93' '4.5' '3.73'
 '3.94' '3.38' '3.59' '3.92' '2.24' '3.31' '2.88' '3.64' '4.07' '4.39'
 '2.49' '2.31' '2.44' '4.63' '3.58' '3.4' '3.95' '3.88' '2.23' '2.15'
 '2.41' '3.16' '4.83' '3.83' '4.13' '4.21' '2.83' '3.02' '4.99' '2.79'
 '2.84' '4.79' '2.07' '4.09' '4.18' '4.51' '4.92' '4.93' '2.2' '4.47'
 '2.39' '4.95' '4.74' '3.32' '2.12' '3.09' '4.48' '4.1' '2.17' '3.28'
 '3.41' '3.08' '3.43' '3.07' '4.05' '3.99' '4.15' '2.8' '2.95' '2.38'
 '3.97' '3.79' '4.61' '3.35' '4.01' '4.46' '2.73' '3.26' '4.52' '3.65'
 '2.58' '4.73' '4.28' '4.53' '3.03' '2.27' '4.27' '3.75' '2.56' '3.76'
 '2.05' '3.72' '2.98' '3.05' '2.82' '2.08' '3.74' '4.23' '4.03' '2.62'
 '3.06' '4.58' '3.89' '4.44' '3.85' '4.34' '4.11' '4.24' '4.55' '2.86'
 '2.1' '2.5' '4.14' '2.71' '2.64' '2.43' '3.5' '2.47' '3.78' '4.26' '3.34'
 '3.22' '3.69' '2.76' '4.75' '4.69' '4.72' '2.51' '4.9' '3.36' '4.84'
 '2.9' '2.91' '?' '3.27' '2.42' '2.59' '2.29' '4.77' '3.61' '3.37' '4.67'
 '3.71' '4.97' '4.08' '4.02' '4.94' '4.96' '4.06' '4.4' '3.15' '3.29'
 '4.29' '4.81' '4.82' '2.52' '4.62' '3.9' '4.16' '3.13' '3.96' '2.81' '5'
 '2.63' '4.89' '2.3' '4.45' '3.25' '2.21' '2.36' '3.49' '4.2' '3.91' '3.6'
 '3.42' '3.3' '4.66' '3.23' '3.81' '2.28' '2.96' '3.52' '4.88' '4.59'
 '2.03' '2.06' '3.55' '2.02' '3.33' '3.77' '4.49' '3.46' '2.61' '3.44'
 '3.7' '2.74' '4.86' '3.63' '3.87' '2.66' '2.25' '4' '2.33' '3.84' '4.68'
 '2.99' '3.17' '2.72' '4.64' '4.04' '2.48' '4.37' '2.13' '3.11' '4.31'
 '4.43' '3.2' '4.32' '3.45' '2.26' '2.6' '2.87' '2.45' '2.04' '4.8' '2.22'
 '4.41' '4.56' '4.57' '3.54' '4.85' '3.18' '4.54' '3.47' '3.21' '3' '4.38'
 '2.92' '2.11' '3.66' '4.17' '2.54' '3.98' '2.16' '2.01' '4.36' '3.53'
 '2.85' '3.62' '4.35' '2.19' '2.46' '2.75' '3.12' '3.68' '2.35' '2.89'
 '4.76' '2.78' '3.01' '2.37' '3.1' '2.57' '3.14' '4.22' '3.82' '3.86'
 '2.65' '3.57' '2.09' '4.91' '3.8' '3.67' '3.24' '4.25' '2.18' '2.14'
 '3.19' '3.04' '2.67']
Valores únicos en Per_Km_Rate: ['0.8' '0.62' '1.21' '0.51' '0.63' '1.71' '1.66' '1.87' '1.78' '1.52'
 '0.58' nan '1.77' '?' '1.26' '0.85' '1.59' '1.97' '0.73' '0.84' '0.82'
 '1.69' '0.78' '0.6' '0.54' '1.75' '1.05' '1.76' '1.33' '1.85' '1.89'
 '0.61' '0.88' '1.5' '1.83' '1.41' '1.95' '0.9' '1.25' '0.72' '1.16' '1'
 '1.28' '1.38' '1.64' '1.57' '1.63' '1.93' '0.86' '0.99' '1.37' '1.03'
 '1.55' '1.34' '1.08' '1.13' '1.82' '1.56' '1.88' '0.91' '1.35' '1.91'
 '1.61' '1.12' '0.57' '0.79' '1.18' '0.95' '1.62' '0.68' '1.3' '1.39'
 '0.69' '1.31' '1.9' '0.96' '1.8' '1.65' '0.87' '0.55' '0.65' '1.06'
 '0.67' '1.11' '1.23' '1.73' '0.76' '1.54' '0.71' '1.29' '1.46' '1.01'
 '1.86' '1.17' '1.24' '1.84' '1.53' '1.79' '0.98' '0.77' '0.7' '0.94'
 '1.36' '1.02' '0.59' '1.45' '1.48' '0.52' '1.32' '0.83' '1.7' '1.49'
 '1.07' '1.19' '1.74' '1.14' '1.94' '0.74' '1.92' '1.22' '1.99' '0.93'
 '0.5' '2' '0.92' '0.75' '1.81' '1.98' '0.97' '1.1' '1.2' '1.15' '1.96'
 '1.72' '1.51' '1.27' '1.43' '1.4' '1.67' '0.53' '1.44' '1.09' '0.81'
 '1.04' '0.56' '1.47' '0.89' '1.42' '0.64' '1.68' '1.58' '0.66']
Valores únicos en Per_Minute_Rate: ['0.32' '0.43' '0.15' '0.48' '?' '0.23' '0.34' '0.47' '0.5' '0.11' '0.21'
 '0.2' '0.41' '0.12' '0.25' '0.3' '0.39' '0.24' '0.35' '0.33' '0.36'
 '0.13' '0.19' '0.44' '0.38' '0.42' '0.26' '0.18' '0.17' '0.29' '0.28'
 '0.31' '0.37' '0.46' '0.16' '0.4' '0.1' '0.27' '0.49' nan '0.45' '0.14'
 '0.22']
Valores únicos en Trip_Duration_Minutes: ['53.82' '40.57' '37.27' '116.81' '22.64' '89.33' '5.05' nan '110.33' '?'
 '26.34' '79.94' '86.95' '84.12' '41.72' '34' '114.93' '111.18' '57.59'
 '57.02' '53.8' '23.03' '54.04' '66.8' '7.59' '56.07' '94.86' '83.21'
 '78.04' '109.6' '7.07' '69.06' '95.55' '67.25' '42.25' '20.67' '107.07'
 '59.14' '105.98' '72.37' '82.53' '97.49' '80.8' '50.78' '64.07' '97.35'
 '47.97' '49.63' '16' '110.18' '15.47' '79.54' '52.52' '51.65' '83.15'
 '12.72' '73.28' '93.78' '100.24' '24.61' '108.2' '106.41' '60.81' '67.33'
 '110.69' '108.49' '56.54' '36.56' '50.21' '49.59' '37.99' '35.89'
 '104.02' '13.03' '82.93' '24.87' '44.62' '12.08' '36.05' '93.37' '106.78'
 '30.48' '58.31' '59.09' '105.46' '92.72' '64' '82.14' '102.45' '6.1'
 '51.33' '109.33' '90.14' '67.43' '65.91' '44.99' '80.37' '53.11' '87.13'
 '104.04' '22.79' '56.93' '51.92' '84.06' '33.73' '78.63' '105.91' '53.09'
 '109.77' '119.21' '17.2' '31.8' '114.29' '115.21' '16.24' '6.72' '23.53'
 '119.54' '25.7' '62.79' '102.57' '7.35' '74.52' '36.86' '104.17' '37.6'
 '83.98' '82.54' '30.47' '9' '52.06' '38.26' '98.03' '97.04' '57.56'
 '74.75' '74.49' '100.12' '53.88' '36.68' '35.48' '66.66' '56.65' '55.61'
 '15.48' '87.64' '29.58' '27.65' '52.47' '31.19' '72.14' '47.72' '56.62'
 '66.77' '28.41' '22.91' '106.25' '54.88' '52.39' '9.1' '68.73' '69.27'
 '86.31' '25.41' '34.01' '98.23' '113.92' '20.63' '62.23' '11.91' '42.43'
 '21.52' '66.38' '21.54' '6.06' '97.94' '74.71' '43.75' '72.33' '41.3'
 '15' '26.63' '54.22' '80.7' '35.34' '6.39' '64.68' '74.66' '115.73'
 '72.79' '59.18' '70.94' '111.71' '42.14' '32.28' '35.2' '63.01' '90.57'
 '62.87' '12.8' '88.21' '97.69' '38.29' '81.37' '54.06' '107.25' '102.2'
 '65.42' '84.52' '106.59' '62.01' '41.02' '91.67' '30.31' '49.68' '104.56'
 '88.31' '51.44' '29.7' '45.94' '37.67' '25.25' '33.99' '57.23' '49.37'
 '117.94' '49.98' '14.2' '15.33' '72.94' '73.93' '53.16' '54.66' '11.2'
 '64.4' '63.05' '22.2' '19.21' '16.62' '75.12' '27.6' '33.91' '24.96'
 '115.15' '103.28' '31.51' '42.67' '29.14' '61.57' '7.26' '82.21' '108.34'
 '23.91' '97.47' '96.08' '19.63' '50.83' '24.57' '34.29' '35.27' '68.97'
 '52.31' '113.99' '19.53' '116.97' '31.52' '93.88' '43.98' '21.45'
 '103.66' '40.52' '70.14' '59.25' '62.02' '89.21' '15.09' '81.84' '108.02'
 '11.65' '21.18' '87.41' '55.29' '51.41' '20.75' '63.28' '19.55' '59.81'
 '92.82' '60.29' '119.08' '83.96' '101.76' '52.71' '93.3' '9.66' '19.13'
 '28.35' '51.22' '102.26' '44.82' '80.28' '86.57' '72.41' '46.08' '71.36'
 '44.36' '119.17' '13.32' '106.03' '39.71' '79.78' '42.84' '50.02' '35.14'
 '44.45' '52.23' '87.85' '9.82' '62.85' '72.19' '110.82' '10.65' '70.95'
 '103.17' '32.82' '105.77' '7.19' '89.23' '112.31' '80.58' '55.49' '10.16'
 '110.81' '59.08' '8.33' '84.33' '60.41' '19.3' '29.64' '12.42' '71.04'
 '76.53' '63.16' '98.97' '75.8' '6.47' '84.95' '70.04' '79.64' '45.28'
 '110.47' '20.41' '82.22' '5.5' '111.33' '17.94' '15.91' '43.3' '47.96'
 '72.29' '55.94' '8.93' '41.76' '84.32' '88.36' '85.28' '40.76' '16.46'
 '36.33' '100.66' '117.75' '61.79' '6.12' '21.11' '42.04' '71.54' '13.64'
 '113.49' '46.98' '109.95' '94.76' '91.88' '74.77' '77.08' '78.37' '77.3'
 '68.68' '118.44' '94.35' '105.33' '29.8' '14.64' '60.53' '64.12' '100.36'
 '70.65' '75.75' '100.22' '23.11' '73.35' '73.27' '23.88' '19.2' '117.71'
 '50.28' '31.15' '24.7' '81.77' '75.09' '79.01' '15.12' '107.76' '49.77'
 '41.04' '58.17' '49.86' '104.31' '111.87' '39.9' '104.35' '94.88'
 '112.04' '33.26' '71.35' '36.57' '99.77' '5.61' '69.95' '44.01' '42.11'
 '79.16' '102.92' '75.06' '103.11' '35.43' '64.74' '56.81' '6.34' '69.03'
 '81.08' '73.07' '89.67' '70.7' '12.68' '18.39' '73.59' '36.62' '14.16'
 '54.4' '68.75' '42.81' '79.03' '43.27' '91.81' '79.6' '78.31' '68.64'
 '6.31' '85.1' '48.24' '113.4' '99.07' '72.58' '28.43' '44.14' '39.05'
 '64.22' '24.02' '117.44' '17.41' '112.17' '110.06' '55.15' '44.17'
 '39.63' '71.5' '37.97' '47.2' '14.65' '11.01' '34.15' '13.54' '16.93'
 '98.49' '9.47' '80.78' '36.34' '105.23' '60.77' '40.14' '64.53' '48.93'
 '69.89' '18.17' '119.65' '53.94' '45.05' '86.67' '46.85' '100.83' '57.24'
 '87.75' '17.36' '102.3' '89.61' '29.35' '41.37' '117.25' '34.54' '57.45'
 '50.68' '114.61' '64.42' '99.2' '67.92' '9.69' '41.23' '71.19' '103.8'
 '31.26' '28.13' '111.09' '103.06' '94.11' '50.16' '63' '58.4' '34.14'
 '63.08' '8.51' '20.16' '106.96' '91.44' '53.63' '64.47' '47.55' '90.19'
 '95.18' '92.78' '88.1' '43.87' '59.03' '43.04' '91.82' '42.88' '20.9'
 '50.89' '117.69' '30.98' '75.4' '13.17' '61.11' '85.75' '64.02' '38.23'
 '14.92' '112.71' '48.49' '71.29' '42.3' '87.36' '20.57' '38.5' '21.64'
 '98.29' '30.6' '87.5' '113.48' '65.69' '67.1' '58.02' '42.48' '59.7'
 '74.32' '118.39' '112.84' '104.15' '58.8' '80.61' '107.93' '50.19'
 '115.6' '52.82' '74.12' '86.63' '114.32' '33.13' '90.81' '64.89' '35.88'
 '94.31' '68.51' '81.01' '42.13' '76' '51.56' '27.81' '115.59' '63.82'
 '89.4' '52.27' '45.84' '51.82' '67.58' '67.5' '62.17' '20.5' '62.05'
 '24.45' '19.51' '112.25' '74.57' '80.84' '51.21' '109.53' '78.36' '93.45'
 '47.38' '115.4' '99.35' '103.2' '24.8' '36.16' '37.85' '36.15' '103.37'
 '8.67' '13.75' '36.5' '27.99' '31.66' '96.76' '5.66' '54.37' '51.91'
 '18.1' '82.76' '85.74' '87.9' '88.77' '5.01' '114.7' '98.63' '108.96'
 '6.8' '112.39' '98.13' '101.28' '15.73' '89.96' '115.39' '83.03' '70.61'
 '113.75' '73.92' '59.78' '112.28' '62.63' '84' '96.07' '72.05' '113.33'
 '12.4' '51.27' '7.7' '66.74' '109.74' '102.35' '19.66' '15.7' '72.77'
 '66.19' '35.63' '108.44' '111.65' '51.3' '107.38' '89.73' '59.73' '19.1'
 '57.22' '89.47' '47.22' '7.17' '16.56' '62.07' '84.35' '43.49' '85.34'
 '85.95' '61.64' '110.21' '61.26' '56.78' '27.93' '40.38' '9.87' '77.86'
 '33.58' '39.98' '93.64' '42.63' '32.85' '24.44' '19.92' '57.18' '84.05'
 '77.83' '10.15' '39.09' '37.22' '21.79' '65.02' '81.33' '48.83' '87.74'
 '43.66' '38.38' '67.24' '7.73' '14.18' '53.07' '113.43' '87.97' '15.13'
 '102.33' '75.26' '99.33' '51.47' '63.88' '68.12' '66.91' '69.98' '114.1'
 '108.76' '105.71' '97.16' '16.33' '35.49' '61.93' '63.09' '91.02' '34.03'
 '89.15' '23.94' '45.41' '35.46' '45.23' '86.46' '68.86' '16.49' '97.58'
 '47.54' '79.58' '88.42' '29.11' '106.74' '75.87' '54.3' '25.97' '113.36'
 '91.83' '28.92' '43.84' '98.11' '85' '93.07' '55.74' '87.39' '49.45'
 '29.3' '117.24' '40.72' '58.01' '82.51' '67.27' '101.99' '92.6' '11.7'
 '119.82' '91.53' '79.89' '103.47' '17.92' '105.79' '28.19' '14' '95.63'
 '101.08' '23.71' '103.25' '64.81' '100.48' '53.21' '27.31' '37.76' '66.1'
 '97.64' '96.01' '71.86' '94.79' '27.05' '10.76' '105.47' '13.69' '33.37'
 '84.96' '52.09' '105.78' '39.27' '6.37' '39.58' '71.48' '48.23' '66.51'
 '105.81' '109.94' '35.59' '58.15' '114.15' '119.84' '32.07' '88.6'
 '48.47' '5.93' '57.97' '61.16' '7.6' '38.81' '69.39' '39.61' '24.22'
 '31.71' '66.5' '27.87' '63.47' '23.1' '82.16' '91.7' '17.7' '13.15'
 '73.79' '35.41' '65.68' '64.51' '111.3' '68.14' '72.04' '51.19' '114.14'
 '94.38' '37.82' '102.08' '54.73' '100.3' '99.63' '26.72' '85.63' '38.42'
 '39.21' '88.44' '31.43' '5.1' '87.25' '24.69' '17.02' '32.31' '48.69'
 '10.13' '116.62' '87.35' '42.17' '41.65' '56.58' '77.02' '21.83' '26.73'
 '103.83' '34.47' '48.72' '105.2' '81.26' '44.3' '83.63' '89.6' '98.52'
 '114.78' '109.57' '63.9' '46.42' '58.48' '84.34' '106.66' '110.59'
 '98.75' '117.57' '106.23' '37.19' '17.18' '17.91' '38.49' '75.63' '97.5'
 '108.41' '76.73' '5.65' '26.43' '16.47' '46.78' '62.66' '9.99' '45.07'
 '25.61' '79.41' '58.39' '61.96' '54.18' '114.94' '29.69']
Valores únicos en Trip_Price: ['36.2624' nan '52.9032' '36.4698' '15.618' '60.2028' '11.2645' '101.1216'
 '75.5657' '14.892' '?' '88.1328' '36.118' '28.9914' '27.4415' '56.716'
 '69.0049' '69.6268' '27.3543' '44.7782' '26.2988' '201.8695092' '39.2366'
 '33.632' '83.6965' '28.2443' '280.8773016' '64.7971' '24.2608' '58.8121'
 '20.7765' '57.28' '61.5552' '54.1018' '35.0164' '40.9225' '60.0471'
 '62.7785' '20.791' '57.0482' '42.9921' '85.884' '29.4758' '30.9982'
 '64.0553' '44.844' '44.1197' '20.1596' '104.1764' '57.0766' '98.3796'
 '41.9343' '72.2695' '99.8989' '10.2366' '32.342' '37.1504' '78.715'
 '29.8609' '59.181' '47.3148' '69.6575' '320.9586636' '61.4595' '68.3748'
 '71.2142' '33.8442' '65.084' '69.5281' '23.5462' '11.3358' '92.8432'
 '36.4388' '61.8883' '104.2421' '18.8626' '45.385' '16.9284' '94.2463'
 '87.6076' '42.8661' '11.2613' '45.8161' '42.9949' '76.2217' '57.9476'
 '59.7613' '55.3948' '29.4658' '40.4165' '63.5611' '105.9418' '60.077'
 '33.0286' '27.865' '40.65' '29.645' '25.7527' '62.4923' '53.9332'
 '58.7766' '73.4155' '31.99' '34.3067' '66.2817' '233.0082852'
 '274.5350868' '37.3559' '99.8038' '29.532' '30.446' '106.0042' '63.4323'
 '19.9744' '62.8678' '52.7821' '82.0828' '63.0611' '51.6275' '25.4826'
 '48.024' '90.5124' '98.6948' '22.7182' '76.2085' '53.056' '22.5446'
 '14.935' '50.696' '85.6182' '30.942' '75.2204' '73.587' '22.8766'
 '67.2293' '110.2544' '327.2176655' '44.7092' '39.4624' '28.5862'
 '27.4942' '76.4286' '54.1556' '29.4228' '40.0207' '36.4958' '35.3572'
 '14.6127' '52.5934' '63.866' '39.5698' '59.9287' '52.6453' '20.3819'
 '76.6192' '35.0028' '57.7533' '40.8518' '66.566' '30.318' '87.6519'
 '51.9016' '19.6645' '48.7802' '86.1412' '12.5567' '54.6218' '19.2643'
 '31.3891' '33.1785' '62.895' '15.0994' '31.8296' '39.4174' '96.939'
 '66.5363' '29.5606' '51.2721' '63.5224' '37.086' '44.7548' '23.4957'
 '19.145' '76.1018' '79.7004' '60.3866' '58.257' '59.7113' '89.0764'
 '77.189' '95.1969' '54.6348' '102.8806' '51.4584' '28.4048' '53.2857'

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35,Morning,Weekday,3.0,Low,Clear,3.56,0.80,0.32,53.82,36.2624
1,47.59,Afternoon,Weekday,1.0,High,Clear,NaN,0.62,0.43,40.57,NaN
2,36.87,Evening,Weekend,1.0,High,Clear,2.70,1.21,0.15,37.27,52.9032
3,30.33,Evening,Weekday,4.0,Low,NaN,3.48,0.51,0.15,116.81,36.4698
4,NaN,Evening,Weekday,3.0,High,Clear,2.93,0.63,0.32,22.64,15.6180

In [15]:
for col in columnas_numericas:
    df[col] = df[col].fillna(df[col].median())

df.head(20)

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35,Morning,Weekday,3.0,Low,Clear,3.56,0.80,0.32,53.82,36.2624
1,47.59,Afternoon,Weekday,1.0,High,Clear,3.52,0.62,0.43,40.57,50.0745
2,36.87,Evening,Weekend,1.0,High,Clear,2.70,1.21,0.15,37.27,52.9032
3,30.33,Evening,Weekday,4.0,Low,NaN,3.48,0.51,0.15,116.81,36.4698
4,25.83,Evening,Weekday,3.0,High,Clear,2.93,0.63,0.32,22.64,15.6180
5,8.64,Afternoon,Weekend,2.0,Medium,Clear,2.55,1.71,0.48,89.33,60.2028
6,3.85,Afternoon,Weekday,4.0,High,Rain,3.51,1.66,0.29,5.05,11.2645
7,43.44,Evening,Weekend,3.0,NaN,Clear,2.97,1.87,0.23,61.86,101.1216
8,30.45,Morning,Weekday,3.0,High,Clear,2.77,1.78,0.34,110.33,50.0745
9,35.70,Afternoon,Weekday,2.0,Low,Rain,3.39,1.52,0.47,61.86,75.5657
10,25.83,Morning,Weekday,4.0,NaN,Clear,2.40,0.58,0.43,26.34,14.8920
11,48.53,Night,Weekday,3.0,Low,Clear,4.78,1.22,0.50,79.94,50.0745
12,41.79,Night,Weekend,3.0,High,Clear,4.60,1.77,0.11,86.95,88.1328
13,11.40,Morning,Weekday,3.0,NaN,Clear,4.12,1.22,0.15,84.12,36.1180
14,9.91,Evening,Weekday,2.0,High,Clear,2.32,1.26,0.34,41.72,28.9914
15,9.99,Night,Weekday,4.0,High,Clear,4.33,0.85,0.43,34.00,27.4415
16,15.91,Morning,Weekday,4.0,Low,Clear,4.42,1.77,0.21,114.93,56.7160
17,26.71,Afternoon,Weekend,4.0,Low,Rain,4.30,1.59,0.20,111.18,69.0049
18,22.17,Night,NaN,4.0,Low,Clear,2.34,1.97,0.41,57.59,69.6268
19,15.27,Morning,NaN,2.0,Low,Clear,3.93,0.73,0.12,61.86,27.3543

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Trip_Distance_km       1000 non-null   float64
 1   Time_of_Day            954 non-null    object
 2   Day_of_Week            954 non-null    object
 3   Passenger_Count        1000 non-null   float64
 4   Traffic_Conditions     954 non-null    object
 5   Weather                954 non-null    object
 6   Base_Fare              1000 non-null   float64
 7   Per_Km_Rate            1000 non-null   float64
 8   Per_Minute_Rate        1000 non-null   float64
 9   Trip_Duration_Minutes  1000 non-null   float64
 10  Trip_Price             1000 non-null   float64
dtypes: float64(7), object(4)
memory usage: 86.1+ KB

In [18]:
columnas_categoricas = ['Time_of_Day', 'Day_of_Week', 'Traffic_Conditions', 'Weather']

for col in columnas_categoricas:
    print(f"Valores únicos en {col}:", df[col].unique())

import numpy as np
df[columnas_categoricas] = df[columnas_categoricas].replace(['?', ' ', ''], np.nan)

df.head(20)

Valores únicos en Time_of_Day: ['Morning' 'Afternoon' 'Evening' 'Night' nan 'evening' 'morning' 'night']
Valores únicos en Day_of_Week: ['Weekday' 'Weekend' nan 'Wkday' 'Wkend' 'weekday' 'WEEKEND' 'WEEKDAY']
Valores únicos en Traffic_Conditions: ['Low' 'High' 'Medium' nan 'L' 'M' 'H']
Valores únicos en Weather: ['Clear' nan 'Rain' 'Snow' 'clear' 'rain' 'snow']

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35,Morning,Weekday,3.0,Low,Clear,3.56,0.80,0.32,53.82,36.2624
1,47.59,Afternoon,Weekday,1.0,High,Clear,3.52,0.62,0.43,40.57,50.0745
2,36.87,Evening,Weekend,1.0,High,Clear,2.70,1.21,0.15,37.27,52.9032
3,30.33,Evening,Weekday,4.0,Low,NaN,3.48,0.51,0.15,116.81,36.4698
4,25.83,Evening,Weekday,3.0,High,Clear,2.93,0.63,0.32,22.64,15.6180
5,8.64,Afternoon,Weekend,2.0,Medium,Clear,2.55,1.71,0.48,89.33,60.2028
6,3.85,Afternoon,Weekday,4.0,High,Rain,3.51,1.66,0.29,5.05,11.2645
7,43.44,Evening,Weekend,3.0,NaN,Clear,2.97,1.87,0.23,61.86,101.1216
8,30.45,Morning,Weekday,3.0,High,Clear,2.77,1.78,0.34,110.33,50.0745
9,35.70,Afternoon,Weekday,2.0,Low,Rain,3.39,1.52,0.47,61.86,75.5657
10,25.83,Morning,Weekday,4.0,NaN,Clear,2.40,0.58,0.43,26.34,14.8920
11,48.53,Night,Weekday,3.0,Low,Clear,4.78,1.22,0.50,79.94,50.0745
12,41.79,Night,Weekend,3.0,High,Clear,4.60,1.77,0.11,86.95,88.1328
13,11.40,Morning,Weekday,3.0,NaN,Clear,4.12,1.22,0.15,84.12,36.1180
14,9.91,Evening,Weekday,2.0,High,Clear,2.32,1.26,0.34,41.72,28.9914
15,9.99,Night,Weekday,4.0,High,Clear,4.33,0.85,0.43,34.00,27.4415
16,15.91,Morning,Weekday,4.0,Low,Clear,4.42,1.77,0.21,114.93,56.7160
17,26.71,Afternoon,Weekend,4.0,Low,Rain,4.30,1.59,0.20,111.18,69.0049
18,22.17,Night,NaN,4.0,Low,Clear,2.34,1.97,0.41,57.59,69.6268
19,15.27,Morning,NaN,2.0,Low,Clear,3.93,0.73,0.12,61.86,27.3543

In [19]:
# Imputación de valores nulos utilizando la Moda para variables categóricas
for col in columnas_categoricas:
    moda = df[col].mode()[0]
    df[col] = df[col].fillna(moda)

df.head(20)

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35,Morning,Weekday,3.0,Low,Clear,3.56,0.80,0.32,53.82,36.2624
1,47.59,Afternoon,Weekday,1.0,High,Clear,3.52,0.62,0.43,40.57,50.0745
2,36.87,Evening,Weekend,1.0,High,Clear,2.70,1.21,0.15,37.27,52.9032
3,30.33,Evening,Weekday,4.0,Low,Clear,3.48,0.51,0.15,116.81,36.4698
4,25.83,Evening,Weekday,3.0,High,Clear,2.93,0.63,0.32,22.64,15.6180
5,8.64,Afternoon,Weekend,2.0,Medium,Clear,2.55,1.71,0.48,89.33,60.2028
6,3.85,Afternoon,Weekday,4.0,High,Rain,3.51,1.66,0.29,5.05,11.2645
7,43.44,Evening,Weekend,3.0,Low,Clear,2.97,1.87,0.23,61.86,101.1216
8,30.45,Morning,Weekday,3.0,High,Clear,2.77,1.78,0.34,110.33,50.0745
9,35.70,Afternoon,Weekday,2.0,Low,Rain,3.39,1.52,0.47,61.86,75.5657
10,25.83,Morning,Weekday,4.0,Low,Clear,2.40,0.58,0.43,26.34,14.8920
11,48.53,Night,Weekday,3.0,Low,Clear,4.78,1.22,0.50,79.94,50.0745
12,41.79,Night,Weekend,3.0,High,Clear,4.60,1.77,0.11,86.95,88.1328
13,11.40,Morning,Weekday,3.0,Low,Clear,4.12,1.22,0.15,84.12,36.1180
14,9.91,Evening,Weekday,2.0,High,Clear,2.32,1.26,0.34,41.72,28.9914
15,9.99,Night,Weekday,4.0,High,Clear,4.33,0.85,0.43,34.00,27.4415
16,15.91,Morning,Weekday,4.0,Low,Clear,4.42,1.77,0.21,114.93,56.7160
17,26.71,Afternoon,Weekend,4.0,Low,Rain,4.30,1.59,0.20,111.18,69.0049
18,22.17,Night,Weekday,4.0,Low,Clear,2.34,1.97,0.41,57.59,69.6268
19,15.27,Morning,Weekday,2.0,Low,Clear,3.93,0.73,0.12,61.86,27.3543

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Trip_Distance_km       1000 non-null   float64
 1   Time_of_Day            1000 non-null   object
 2   Day_of_Week            1000 non-null   object
 3   Passenger_Count        1000 non-null   float64
 4   Traffic_Conditions     1000 non-null   object
 5   Weather                1000 non-null   object
 6   Base_Fare              1000 non-null   float64
 7   Per_Km_Rate            1000 non-null   float64
 8   Per_Minute_Rate        1000 non-null   float64
 9   Trip_Duration_Minutes  1000 non-null   float64
 10  Trip_Price             1000 non-null   float64
dtypes: float64(7), object(4)
memory usage: 86.1+ KB