<a href="https://colab.research.google.com/github/jmora420-hue/Ciencia_de_datos/blob/main/Tictanic_Ejercicio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [60]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [61]:
columnas_numericas = [
    'PassengerId', 'Survived', 'Pclass',
    'Age', 'SibSp', 'Parch', 'Fare'
]

for col in columnas_numericas:
    print(f"Valores únicos en {col}:", df[col].unique())

for col in columnas_numericas:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df.head(40)

Valores únicos en PassengerId: [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252
 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270
 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288
 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306
 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324
 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342
 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360
 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378
 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396
 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414
 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432
 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450
 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468
 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486
 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503 504
 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522
 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539 540
 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558
 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575 576
 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593 594
 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611 612
 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629 630
 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647 648
 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665 666
 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683 684
 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701 702
 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719 720
 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737 738
 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755 756
 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773 774
 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791 792
 793 794 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809 810
 811 812 813 814 815 816 817 818 819 820 821 822 823 824 825 826 827 828
 829 830 831 832 833 834 835 836 837 838 839 840 841 842 843 844 845 846
 847 848 849 850 851 852 853 854 855 856 857 858 859 860 861 862 863 864
 865 866 867 868 869 870 871 872 873 874 875 876 877 878 879 880 881 882
 883 884 885 886 887 888 889 890 891]
Valores únicos en Survived: [0 1]
Valores únicos en Pclass: [3 1 2]
Valores únicos en Age: [22.   38.   26.   35.     nan 54.    2.   27.   14.    4.   58.   20.
 39.   55.   31.   34.   15.   28.    8.   19.   40.   66.   42.   21.
 18.    3.    7.   49.   29.   65.   28.5   5.   11.   45.   17.   32.
 16.   25.    0.83 30.   33.   23.   24.   46.   59.   71.   37.   47.
 14.5  70.5  32.5  12.    9.   36.5  51.   55.5  40.5  44.    1.   61.
 56.   50.   36.   45.5  20.5  62.   41.   52.   63.   23.5   0.92 43.
 60.   10.   64.   13.   48.    0.75 53.   57.   80.   70.   24.5   6.
  0.67 30.5   0.42 34.5  74.  ]
Valores únicos en SibSp: [1 0 3 4 2 5 8]
Valores únicos en Parch: [0 1 2 5 3 4 6]
Valores únicos en Fare: [  7.25    71.2833   7.925   53.1      8.05     8.4583  51.8625  21.075
  11.1333  30.0708  16.7     26.55    31.275    7.8542  16.      29.125
  13.      18.       7.225   26.       8.0292  35.5     31.3875 263.
   7.8792   7.8958  27.7208 146.5208   7.75    10.5     82.1708  52.
   7.2292  11.2417   9.475   21.      41.5792  15.5     21.6792  17.8
  39.6875   7.8     76.7292  61.9792  27.75    46.9     80.      83.475
  27.9     15.2458   8.1583   8.6625  73.5     14.4542  56.4958   7.65
  29.      12.475    9.       9.5      7.7875  47.1     15.85    34.375
  61.175   20.575   34.6542  63.3583  23.      77.2875   8.6542   7.775
  24.15     9.825   14.4583 247.5208   7.1417  22.3583   6.975    7.05
  14.5     15.0458  26.2833   9.2167  79.2      6.75    11.5     36.75
   7.7958  12.525   66.6      7.3125  61.3792   7.7333  69.55    16.1
  15.75    20.525   55.      25.925   33.5     30.6958  25.4667  28.7125
   0.      15.05    39.      22.025   50.       8.4042   6.4958  10.4625
  18.7875  31.     113.275   27.      76.2917  90.       9.35    13.5
   7.55    26.25    12.275    7.125   52.5542  20.2125  86.5    512.3292
  79.65   153.4625 135.6333  19.5     29.7     77.9583  20.25    78.85
  91.0792  12.875    8.85   151.55    30.5     23.25    12.35   110.8833
 108.9     24.      56.9292  83.1583 262.375   14.     164.8667 134.5
   6.2375  57.9792  28.5    133.65    15.9      9.225   35.      75.25
  69.3     55.4417 211.5      4.0125 227.525   15.7417   7.7292  12.
 120.      12.65    18.75     6.8583  32.5      7.875   14.4     55.9
   8.1125  81.8583  19.2583  19.9667  89.1042  38.5      7.725   13.7917
   9.8375   7.0458   7.5208  12.2875   9.5875  49.5042  78.2667  15.1
   7.6292  22.525   26.2875  59.4      7.4958  34.0208  93.5    221.7792
 106.425   49.5     71.      13.8625   7.8292  39.6     17.4     51.4792
  26.3875  30.      40.125    8.7125  15.      33.      42.4     15.55
  65.      32.3208   7.0542   8.4333  25.5875   9.8417   8.1375  10.1708
 211.3375  57.      13.4167   7.7417   9.4833   7.7375   8.3625  23.45
  25.9292   8.6833   8.5167   7.8875  37.0042   6.45     6.95     8.3
   6.4375  39.4     14.1083  13.8583  50.4958   5.       9.8458  10.5167]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,7.8958,NaN,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,NaN,C
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
32,33,1,3,"Glynn, Miss. Mary Agatha",female,NaN,0,0,335677,7.7500,NaN,Q
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28.0,1,0,PC 17604,82.1708,NaN,C
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,NaN,S
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
37,38,0,3,"Cann, Mr. Ernest Charles",male,21.0,0,0,A./5. 2152,8.0500,NaN,S
38,39,0,3,"Vander Planke, Miss. Augusta Maria",female,18.0,2,0,345764,18.0000,NaN,S
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.0,1,0,2651,11.2417,NaN,C

In [62]:
promediospGen = df.groupby('Sex')['Age'].mean().round()

def imputar_edad(fila):
    if pd.isnull(fila['Age']):
        return promediospGen[fila['Sex']]
    else:
        return fila['Age']

df['Age'] = df.apply(imputar_edad, axis=1)

df['Age'] = df['Age'].astype(int)

df.head(40)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,31,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,31,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,28,0,0,2649,7.2250,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28,0,0,113788,35.5000,A6,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8,3,1,349909,21.0750,NaN,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38,1,5,347077,31.3875,NaN,S
26,27,0,3,"Emir, Mr. Farred Chehab",male,31,0,0,2631,7.2250,NaN,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19,3,2,19950,263.0000,C23 C25 C27,S
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,28,0,0,330959,7.8792,NaN,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,31,0,0,349216,7.8958,NaN,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40,0,0,PC 17601,27.7208,NaN,C
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,28,1,0,PC 17569,146.5208,B78,C
32,33,1,3,"Glynn, Miss. Mary Agatha",female,28,0,0,335677,7.7500,NaN,Q
33,34,0,2,"Wheadon, Mr. Edward H",male,66,0,0,C.A. 24579,10.5000,NaN,S
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28,1,0,PC 17604,82.1708,NaN,C
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42,1,0,113789,52.0000,NaN,S
36,37,1,3,"Mamee, Mr. Hanna",male,31,0,0,2677,7.2292,NaN,C
37,38,0,3,"Cann, Mr. Ernest Charles",male,21,0,0,A./5. 2152,8.0500,NaN,S
38,39,0,3,"Vander Planke, Miss. Augusta Maria",female,18,2,0,345764,18.0000,NaN,S
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14,1,0,2651,11.2417,NaN,C

In [63]:
df['Fare'] = pd.to_numeric(df['Fare'], errors='coerce')
df['Fare'] = df['Fare'].fillna(df['Fare'].median())
df['Fare'] = df['Fare'].round(2)

In [65]:
#df['Ticket'] = df['Ticket'].astype(str).str.extract(r'(\d+)$')[0] #"Dejarlo de comentario a no ser que sea la primera limpieza"
df['Ticket'] = pd.to_numeric(df['Ticket'], errors='coerce')
df['Ticket'] = df['Ticket'].astype('Int64')
df.head(40)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,21171,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,17599,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,3101282,7.92,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.05,NaN,S
5,6,0,3,"Moran, Mr. James",male,31,0,0,330877,8.46,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54,0,0,17463,51.86,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2,3,1,349909,21.08,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27,0,2,347742,11.13,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14,1,0,237736,30.07,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4,1,1,9549,16.70,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58,0,0,113783,26.55,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20,0,0,2151,8.05,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39,1,5,347082,31.28,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14,0,0,350406,7.85,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55,0,0,248706,16.00,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2,4,1,382652,29.12,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,31,0,0,244373,13.00,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31,1,0,345763,18.00,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,28,0,0,2649,7.22,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35,0,0,239865,26.00,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34,0,0,248698,13.00,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15,0,0,330923,8.03,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28,0,0,113788,35.50,A6,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8,3,1,349909,21.08,NaN,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38,1,5,347077,31.39,NaN,S
26,27,0,3,"Emir, Mr. Farred Chehab",male,31,0,0,2631,7.22,NaN,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19,3,2,19950,263.00,C23 C25 C27,S
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,28,0,0,330959,7.88,NaN,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,31,0,0,349216,7.90,NaN,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40,0,0,17601,27.72,NaN,C
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,28,1,0,17569,146.52,B78,C
32,33,1,3,"Glynn, Miss. Mary Agatha",female,28,0,0,335677,7.75,NaN,Q
33,34,0,2,"Wheadon, Mr. Edward H",male,66,0,0,24579,10.50,NaN,S
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28,1,0,17604,82.17,NaN,C
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42,1,0,113789,52.00,NaN,S
36,37,1,3,"Mamee, Mr. Hanna",male,31,0,0,2677,7.23,NaN,C
37,38,0,3,"Cann, Mr. Ernest Charles",male,21,0,0,2152,8.05,NaN,S
38,39,0,3,"Vander Planke, Miss. Augusta Maria",female,18,2,0,345764,18.00,NaN,S
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14,1,0,2651,11.24,NaN,C

In [66]:
df['Cabin'] = df['Cabin'].astype(str).str.split(' ').str[0]

# 2. Al convertir a texto, los nulos se vuelven la palabra 'nan', los regresamos a nulos reales
df['Cabin'] = df['Cabin'].replace('nan', np.nan)

# 3. Aplicar Last Observation Carried Forward (LOCF) para rellenar vacíos con el último conocido
df['Cabin'] = df['Cabin'].ffill()

df.head(40)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,21171,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,17599,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,3101282,7.92,C85,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.05,C123,S
5,6,0,3,"Moran, Mr. James",male,31,0,0,330877,8.46,C123,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54,0,0,17463,51.86,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2,3,1,349909,21.08,E46,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27,0,2,347742,11.13,E46,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14,1,0,237736,30.07,E46,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4,1,1,9549,16.70,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58,0,0,113783,26.55,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20,0,0,2151,8.05,C103,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39,1,5,347082,31.28,C103,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14,0,0,350406,7.85,C103,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55,0,0,248706,16.00,C103,S
16,17,0,3,"Rice, Master. Eugene",male,2,4,1,382652,29.12,C103,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,31,0,0,244373,13.00,C103,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31,1,0,345763,18.00,C103,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,28,0,0,2649,7.22,C103,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35,0,0,239865,26.00,C103,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34,0,0,248698,13.00,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15,0,0,330923,8.03,D56,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28,0,0,113788,35.50,A6,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8,3,1,349909,21.08,A6,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38,1,5,347077,31.39,A6,S
26,27,0,3,"Emir, Mr. Farred Chehab",male,31,0,0,2631,7.22,A6,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19,3,2,19950,263.00,C23,S
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,28,0,0,330959,7.88,C23,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,31,0,0,349216,7.90,C23,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40,0,0,17601,27.72,C23,C
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,28,1,0,17569,146.52,B78,C
32,33,1,3,"Glynn, Miss. Mary Agatha",female,28,0,0,335677,7.75,B78,Q
33,34,0,2,"Wheadon, Mr. Edward H",male,66,0,0,24579,10.50,B78,S
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28,1,0,17604,82.17,B78,C
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42,1,0,113789,52.00,B78,S
36,37,1,3,"Mamee, Mr. Hanna",male,31,0,0,2677,7.23,B78,C
37,38,0,3,"Cann, Mr. Ernest Charles",male,21,0,0,2152,8.05,B78,S
38,39,0,3,"Vander Planke, Miss. Augusta Maria",female,18,2,0,345764,18.00,B78,S
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14,1,0,2651,11.24,B78,C

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    int64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       887 non-null    Int64
 9   Fare         891 non-null    float64
 10  Cabin        890 non-null    object
 11  Embarked     889 non-null    object
dtypes: Int64(1), float64(1), int64(6), object(4)
memory usage: 84.5+ KB

In [68]:
#Quitamos las filas que todavía tengan algún NaN
"""Como ya imputamos casi todo, los que quedan son tan poquitos que
es más práctico y seguro eliminarlos."""
df.dropna(inplace=True)

print(df.isnull().sum())

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [69]:
df.head(40)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,17599,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,3101282,7.92,C85,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.05,C123,S
5,6,0,3,"Moran, Mr. James",male,31,0,0,330877,8.46,C123,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54,0,0,17463,51.86,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2,3,1,349909,21.08,E46,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27,0,2,347742,11.13,E46,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14,1,0,237736,30.07,E46,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4,1,1,9549,16.70,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58,0,0,113783,26.55,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20,0,0,2151,8.05,C103,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39,1,5,347082,31.28,C103,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14,0,0,350406,7.85,C103,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55,0,0,248706,16.00,C103,S
16,17,0,3,"Rice, Master. Eugene",male,2,4,1,382652,29.12,C103,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,31,0,0,244373,13.00,C103,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31,1,0,345763,18.00,C103,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,28,0,0,2649,7.22,C103,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35,0,0,239865,26.00,C103,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34,0,0,248698,13.00,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15,0,0,330923,8.03,D56,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28,0,0,113788,35.50,A6,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8,3,1,349909,21.08,A6,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38,1,5,347077,31.39,A6,S
26,27,0,3,"Emir, Mr. Farred Chehab",male,31,0,0,2631,7.22,A6,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19,3,2,19950,263.00,C23,S
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,28,0,0,330959,7.88,C23,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,31,0,0,349216,7.90,C23,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40,0,0,17601,27.72,C23,C
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,28,1,0,17569,146.52,B78,C
32,33,1,3,"Glynn, Miss. Mary Agatha",female,28,0,0,335677,7.75,B78,Q
33,34,0,2,"Wheadon, Mr. Edward H",male,66,0,0,24579,10.50,B78,S
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28,1,0,17604,82.17,B78,C
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42,1,0,113789,52.00,B78,S
36,37,1,3,"Mamee, Mr. Hanna",male,31,0,0,2677,7.23,B78,C
37,38,0,3,"Cann, Mr. Ernest Charles",male,21,0,0,2152,8.05,B78,S
38,39,0,3,"Vander Planke, Miss. Augusta Maria",female,18,2,0,345764,18.00,B78,S
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14,1,0,2651,11.24,B78,C
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40,1,0,7546,9.48,B78,S

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 884 entries, 1 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  884 non-null    int64
 1   Survived     884 non-null    int64
 2   Pclass       884 non-null    int64
 3   Name         884 non-null    object
 4   Sex          884 non-null    object
 5   Age          884 non-null    int64
 6   SibSp        884 non-null    int64
 7   Parch        884 non-null    int64
 8   Ticket       884 non-null    Int64
 9   Fare         884 non-null    float64
 10  Cabin        884 non-null    object
 11  Embarked     884 non-null    object
dtypes: Int64(1), float64(1), int64(6), object(4)
memory usage: 90.6+ KB

Yo creo que Jack NO hubiera spbrevivido si se subía a la tabla con Rose, esto directamente por el peso extra que él hubiera añadido y que hubiera evitado que la puerta flotara de tal manera para que ambos sobrevivieran.